### ISSUE TITLE
pypi release?

### ISSUE THREAD

**Issue by hellysmile** [and800/aioreloader#2]

**Comment by and800** [comment]
This lib is in early development stage and almost not tested, so I've not published it yet.
Moreover, the idea was not to make standalone package, but rather a part of one of aio libraries.

But if you think it may be useful for you, I will try to find some time today to make it look like a normal package and publish it. I will write here when it's done.

**Comment by hellysmile** [comment]
@and800 Hey! it is working fine, just a couple of fixes here https://github.com/and800/aioreloader/pull/1
please, take a look on it and let's make pypi release!

**Comment by and800** [comment]
📦 Done. Look for `aioreloader`.

Also be aware of breaking changes on minor ver increment, it's still 0.x
